---
- name: Linux system report
  hosts: all
  gather_facts: true

  tasks:
    - name: Display system information
      ansible.builtin.debug:
        msg:
          - "Inventory name: {{ inventory_hostname }}"
          - "Hostname: {{ ansible_facts['hostname'] }}"
          - "Operating system: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
          - "Kernel: {{ ansible_facts['kernel'] }}"
          - "Architecture: {{ ansible_facts['architecture'] }}"
          - "Processors: {{ ansible_facts['processor_vcpus'] }}"
          - "Memory: {{ ansible_facts['memtotal_mb'] }} MB"
          - "Virtualization: {{ ansible_facts['virtualization_type'] }}"
